import type { Metadata } from "next";
import { Geist_Mono, Nunito } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../components/theme-provider";

import Providers from "./providers";

const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{  children: React.ReactNode;  }>) {
  return (
    <html
      lang="en"
      className={`${nunito.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">

        {/* ganti dark/light di sini ya... */}
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
        >
          <Providers>
              {children}
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
